openapi: 3.0.3
info:
  title: Inditex Prices API
  version: 1.0.0
  
tags:
  - name: Prices
    description: Prices API for Inditex java test
    
paths:
  /prices:
    get:
      tags:
        - Prices
      operationId: getPrice
      summary: Obtain te price detail filtered by brand, product and application date
      parameters:
        - name: brandId
          in: query
          required: true
          schema:
            type: string
            format: UUID
        - name: productId
          in: query
          required: true
          schema:
            type: string
            format: UUID
        - name: applicationDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Price detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceDetail'
        '400':
          $ref: "#/components/responses/BadRequest"
        "404":
            $ref: "#/components/responses/NotFound"
        "500":
            $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    PriceDetail:
      type: object
      properties:
        productId:
          type: string
          format: UUID
        brandId:
          type: string
          format: UUID
        priceList:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: double
    Error:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
          maximum: 255
        detail:
          maximum: 255
        instance:
          type: string
    ProblemDetail:
      description: A problemDetail Details object
      type: object
      additionalProperties: true
      properties:
        title:
          type: string
          maxLength: 500
          description: A short summary of the problem
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: The HTTP Status Code generated by the origin server for this occurrence of the problem
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          maxLength: 5000
          description: A human-readable explanation specific to this occurrence of the problem
          example: Requested service not available
        instance:
          type: string
          maxLength: 2000
          description: URI reference that identifies the specific occurrence of the problem
          example: /prices
      example:
        title: Bad Request
        status: 400
        detail: Requested service not available
        instance: /prices
  responses:
    BadRequest:
      description: 'Bad request. One or more parameters has an invalid value.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: about:blank
            title: Bad Request
            status: 400
            detail: The request could not be understood by the server due to malformed syntax
            instance: /prices
    NotFound:
      description: Resource not found
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
          example:
            type: about:blank
            title: Internal Server Error
            status: 500
            detail: The server encountered an unexpected condition
            instance: /iopcljava/v1/product


